// Curated starter set of common generic OBD-II fault codes (UK garage focus —
// petrol + diesel). Generic codes (P0xxx) are a public standard, same meaning on
// every make. Expand this list later with the full dataset / manufacturer-specific
// (P1xxx) codes. Each entry: meaning, severity, common causes, common fixes.

export type Severity = 'low' | 'medium' | 'high'

export interface FaultCode {
  code: string
  title: string
  severity: Severity
  causes: string[]
  fixes: string[]
}

export const FAULT_CODES: FaultCode[] = [
  { code: 'P0300', title: 'Random / multiple cylinder misfire', severity: 'high',
    causes: ['Worn spark plugs or coils', 'Vacuum leak', 'Low fuel pressure', 'Carbon-fouled injectors', 'Timing fault'],
    fixes: ['Read live data for the misfiring cylinder(s)', 'Renew plugs & test coils', 'Smoke-test for vacuum leaks', 'Check fuel pressure & injectors'] },
  { code: 'P0301', title: 'Cylinder 1 misfire (P0302–P0308 = cyl 2–8)', severity: 'high',
    causes: ['Faulty coil or plug on that cylinder', 'Injector fault', 'Low compression', 'Wiring to coil/injector'],
    fixes: ['Swap coil/plug to another cylinder and see if the misfire follows', 'Compression / leak-down test', 'Check injector & wiring'] },
  { code: 'P0420', title: 'Catalyst efficiency below threshold (Bank 1)', severity: 'medium',
    causes: ['Worn/failed catalytic converter', 'Faulty rear O2 (lambda) sensor', 'Exhaust leak before/after cat', 'Underlying misfire or rich/lean running'],
    fixes: ['Check for exhaust leaks first (cheapest)', 'Compare front/rear O2 readings', 'Rule out misfire/fuelling before condemning the cat', 'Renew cat if genuinely failed'] },
  { code: 'P0430', title: 'Catalyst efficiency below threshold (Bank 2)', severity: 'medium',
    causes: ['As P0420 but Bank 2 (V engines)', 'Failed cat / rear O2 sensor', 'Exhaust leak'],
    fixes: ['Same diagnosis as P0420 on Bank 2'] },
  { code: 'P0171', title: 'System too lean (Bank 1)', severity: 'medium',
    causes: ['Vacuum / intake air leak', 'Dirty MAF sensor', 'Weak fuel pump / blocked filter', 'Leaking injector seals'],
    fixes: ['Smoke-test intake for leaks', 'Clean or renew MAF', 'Check fuel pressure', 'Inspect PCV & intake boots'] },
  { code: 'P0174', title: 'System too lean (Bank 2)', severity: 'medium',
    causes: ['As P0171 on Bank 2', 'Intake leak', 'MAF / fuel delivery'],
    fixes: ['Same as P0171, Bank 2'] },
  { code: 'P0172', title: 'System too rich (Bank 1)', severity: 'medium',
    causes: ['Leaking injector', 'High fuel pressure', 'Faulty MAF/MAP', 'Faulty coolant temp sensor'],
    fixes: ['Check fuel pressure & injectors', 'Test MAF/MAP & coolant sensor', 'Inspect for contaminated oil (fuel dilution)'] },
  { code: 'P0101', title: 'Mass Air Flow (MAF) circuit range/performance', severity: 'medium',
    causes: ['Dirty/faulty MAF sensor', 'Air leak after MAF', 'Blocked air filter'],
    fixes: ['Clean MAF with proper cleaner', 'Check intake boot for splits', 'Renew air filter / MAF if faulty'] },
  { code: 'P0113', title: 'Intake Air Temp (IAT) sensor high input', severity: 'low',
    causes: ['Faulty IAT sensor', 'Wiring open circuit', 'Poor connector'],
    fixes: ['Check sensor resistance & wiring', 'Renew IAT sensor'] },
  { code: 'P0128', title: 'Coolant thermostat (below regulating temp)', severity: 'low',
    causes: ['Thermostat stuck open', 'Faulty coolant temp sensor', 'Low coolant'],
    fixes: ['Renew thermostat (most common)', 'Verify coolant temp sensor reading', 'Top up / bleed coolant'] },
  { code: 'P0131', title: 'O2 sensor low voltage (Bank 1 Sensor 1)', severity: 'medium',
    causes: ['Faulty front lambda sensor', 'Exhaust leak', 'Wiring/short to ground'],
    fixes: ['Check live O2 data', 'Inspect wiring & exhaust', 'Renew lambda sensor'] },
  { code: 'P0133', title: 'O2 sensor slow response (Bank 1 Sensor 1)', severity: 'medium',
    causes: ['Aged/lazy lambda sensor', 'Exhaust leak', 'Contaminated sensor'],
    fixes: ['Renew front lambda sensor', 'Check for exhaust leaks'] },
  { code: 'P0135', title: 'O2 sensor heater circuit (Bank 1 Sensor 1)', severity: 'low',
    causes: ['Failed sensor heater element', 'Blown fuse', 'Wiring fault'],
    fixes: ['Check heater fuse & supply', 'Renew lambda sensor'] },
  { code: 'P0340', title: 'Camshaft position sensor circuit', severity: 'high',
    causes: ['Faulty cam sensor', 'Wiring/connector fault', 'Timing belt/chain jumped', 'Reluctor ring damage'],
    fixes: ['Check sensor & wiring', 'Verify cam/crank correlation', 'Renew sensor; check timing'] },
  { code: 'P0335', title: 'Crankshaft position sensor circuit', severity: 'high',
    causes: ['Faulty crank sensor', 'Damaged reluctor/trigger wheel', 'Wiring fault'],
    fixes: ['Check sensor signal on scope/live data', 'Renew crank sensor', 'Inspect trigger wheel'] },
  { code: 'P0016', title: 'Crankshaft/Camshaft correlation (Bank 1)', severity: 'high',
    causes: ['Timing chain stretch / jumped', 'VVT/cam phaser fault', 'Cam or crank sensor', 'Oil control valve'],
    fixes: ['Check timing alignment', 'Test VVT solenoid & oil pressure', 'Renew chain/tensioner if stretched'] },
  { code: 'P0011', title: 'Camshaft timing over-advanced (Bank 1)', severity: 'medium',
    causes: ['VVT/VANOS solenoid fault', 'Low/dirty oil', 'Cam phaser fault', 'Wiring'],
    fixes: ['Renew/clean VVT solenoid', 'Service oil & filter', 'Check oil pressure'] },
  { code: 'P0401', title: 'EGR insufficient flow', severity: 'medium',
    causes: ['Carboned-up EGR valve/passages', 'Faulty EGR valve', 'Blocked EGR cooler', 'Vacuum/electrical fault'],
    fixes: ['Clean or renew EGR valve', 'Clear carbon from passages', 'Check EGR cooler & control'] },
  { code: 'P0402', title: 'EGR excessive flow', severity: 'medium',
    causes: ['EGR valve stuck open', 'Faulty DPFE/EGR sensor', 'Carbon holding valve open'],
    fixes: ['Clean/renew EGR valve', 'Check EGR position sensor'] },
  { code: 'P0299', title: 'Turbocharger underboost', severity: 'high',
    causes: ['Boost leak (split hose/intercooler)', 'Sticking VNT/wastegate actuator', 'Faulty boost sensor', 'Blocked DPF (diesel)'],
    fixes: ['Pressure-test boost pipes & intercooler', 'Check VNT/actuator operation', 'Inspect DPF backpressure'] },
  { code: 'P0234', title: 'Turbocharger overboost', severity: 'high',
    causes: ['Sticking VNT vanes', 'Wastegate/actuator fault', 'Boost control solenoid'],
    fixes: ['Check VNT mechanism & actuator', 'Test boost control solenoid'] },
  { code: 'P0087', title: 'Fuel rail/system pressure too low', severity: 'high',
    causes: ['Worn high-pressure fuel pump', 'Blocked fuel filter', 'Leaking injector/regulator', 'Weak lift pump (diesel)'],
    fixes: ['Renew fuel filter', 'Test rail pressure & pump', 'Injector leak-back test (diesel)'] },
  { code: 'P0088', title: 'Fuel rail/system pressure too high', severity: 'high',
    causes: ['Faulty pressure regulator/PRV', 'Blocked return', 'Pressure sensor fault'],
    fixes: ['Check regulator & sensor', 'Inspect return line'] },
  { code: 'P2002', title: 'DPF efficiency below threshold (Bank 1)', severity: 'high',
    causes: ['Blocked/full diesel particulate filter', 'Failed pressure/temp sensor', 'Lots of short journeys (no regen)', 'Underlying EGR/turbo fault'],
    fixes: ['Read soot/ash load & backpressure', 'Forced regen if soot (not ash)', 'Fix root cause before/with DPF', 'Clean or renew DPF if ash-loaded'] },
  { code: 'P244A', title: 'DPF differential pressure too low', severity: 'medium',
    causes: ['DPF pressure sensor/pipe fault', 'Cracked/removed DPF substrate', 'Blocked sensor hoses'],
    fixes: ['Check DPF pressure pipes for blockage/leak', 'Test pressure sensor', 'Inspect DPF integrity'] },
  { code: 'P2463', title: 'DPF soot accumulation', severity: 'high',
    causes: ['Excess soot (failed regens)', 'Short-journey use', 'EGR/turbo/injector fault preventing regen'],
    fixes: ['Forced regeneration', 'Diagnose why regens fail', 'Clean/renew DPF if needed'] },
  { code: 'P0440', title: 'EVAP system (general)', severity: 'low',
    causes: ['Loose/faulty fuel cap', 'EVAP hose leak', 'Faulty purge/vent valve'],
    fixes: ['Check & reseat fuel cap first', 'Smoke-test EVAP system', 'Renew faulty valve'] },
  { code: 'P0442', title: 'EVAP small leak', severity: 'low',
    causes: ['Loose fuel cap', 'Small EVAP hose/seal leak', 'Faulty vent valve'],
    fixes: ['Renew fuel cap', 'Smoke-test for the leak'] },
  { code: 'P0455', title: 'EVAP gross (large) leak', severity: 'low',
    causes: ['Missing/loose fuel cap', 'Disconnected/split EVAP hose', 'Failed purge valve stuck open'],
    fixes: ['Check fuel cap & large hoses', 'Smoke-test EVAP'] },
  { code: 'P0500', title: 'Vehicle speed sensor (VSS)', severity: 'medium',
    causes: ['Faulty speed sensor', 'Wiring fault', 'ABS sensor/ring (on some)'],
    fixes: ['Check VSS signal & wiring', 'Inspect ABS sensors if shared'] },
  { code: 'P0562', title: 'System voltage low', severity: 'medium',
    causes: ['Failing battery', 'Faulty alternator', 'Corroded earth/charging cables', 'High resistance connections'],
    fixes: ['Battery & charging system test', 'Check earths & charging cables', 'Renew alternator/battery as needed'] },
  { code: 'P0700', title: 'Transmission control system (malfunction)', severity: 'medium',
    causes: ['Stored fault in the TCM (companion code)', 'Low/old ATF', 'Solenoid/sensor fault'],
    fixes: ['Read the manufacturer-specific TCM codes alongside this', 'Check ATF level/condition', 'Diagnose the companion code'] },
  { code: 'P0741', title: 'Torque converter clutch performance', severity: 'medium',
    causes: ['Worn torque converter', 'Faulty TCC solenoid', 'Low/dirty ATF', 'Valve body issue'],
    fixes: ['Service ATF & filter', 'Test TCC solenoid', 'Inspect converter/valve body'] },
  { code: 'P0226', title: 'Throttle/pedal position sensor (B) range', severity: 'medium',
    causes: ['Faulty throttle body / pedal sensor', 'Wiring fault', 'Carbon in throttle body'],
    fixes: ['Clean throttle body & relearn', 'Check pedal/throttle sensors & wiring'] },
  { code: 'P0606', title: 'ECM/PCM processor fault', severity: 'high',
    causes: ['Internal ECU fault', 'Poor power/earth to ECU', 'Water ingress to ECU'],
    fixes: ['Check ECU power/earths first', 'Inspect for water damage', 'ECU repair/replacement if internal'] },
]
